### PR TITLE
feat: fetch from backend

### PR DESCRIPTION
**Pull request by unnamedsunshine**
- **update packages**
- **fix alembic head upgrade**

### CODE REVIEW

**Comment by winlinworks** [comment]
@unnamedsunshine is this ready for review?

**Comment by unnamedsunshine** [comment]
@winlinworks, it is ready for review. Is it typical to send a message here to those needing to review it when it is ready?

**Comment by winlinworks** [comment]
> @winlinworks, it is ready for review. Is it typical to send a message here to those needing to review it when it is ready?

@unnamedsunshine yes, you should mark the PR as ready for review so reviewers know it's ready, as well as pinging them in chat with a link to the PR in case the auto notification doesn't go through

**Review by winlinworks — APPROVED** [review]
lgtm

**Pull request merged**
